FROM golang:1.26.2-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o wall-app main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/wall-app .
COPY --from=builder /app/index.html .

EXPOSE 8080
CMD [ "./wall-app" ]
